services:
  webapp:
    build: .
    container_name: m300-webapp
    ports:
      - "80:80"
    restart: always

  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: m300-monitoring
    ports:
      - "3001:3001"
    volumes:
      - uptime-kuma-data:/app/data
    restart: always

volumes:
  uptime-kuma-data: